### ISSUE TITLE
Fix decimal height differences

### ISSUE THREAD

**Issue by melisabok** [melisabok/tabula-java#6]
TestCommandLineApp.testExtractJSONWithArea
TestWriters.testJSONWriter

<img width="913" alt="screen shot 2017-01-28 at 4 23 46 pm" src="https://cloud.githubusercontent.com/assets/545506/22399948/471093bc-e576-11e6-8aba-c7b462977f59.png">

**Comment by melisabok** [comment]
@jazzido

I found most of the JSON tests failing because of differences in the decimals. 

I decided to:
- Update the JSON test files with the new decimal values.
- Test the same pdf files of the JSON test using the CSV writers, to be sure the table output is still the same.

**Comment by jazzido** [comment]
Yeah, that's something that we should have addressed a long time ago. It is absolutely overkill (or just plain _wrong_) to use `float` to measure distances.

Another possible solution would be to round to _n_ decimal places before comparing.

**Comment by melisabok** [comment]
Yes, in that case we should change the JSON writer, right?

or change the way that we compare json outputs, currently is comparing jsons as strings, we can build a JSON comparator that does the rounding in the comparison.

**Comment by jazzido** [comment]
I guess the *right* way would be to refactor the entire codebase to use fixed precision numbers instead of floats, but that's too big of a project. 

I like the idea of the JSON comparator, but that's also quite a lot of work. I'd say that as long the differences are small, and extracted tables are identical to those in `master`, let's just replace the JSON files.
